# From https://github.com/E4S-Project/e4s/tree/master/environments/21.11
packages:
  all:
    providers:
      blas:
      - openblas
      mpi:
      - mpich
    target:
    - x86_64
    variants: +mpi
  cuda:
    version:
    - 11.4.2
  binutils:
    variants: +ld +gold +headers +libiberty ~nls +plugins
    version:
    - 2.36.1
  boost:
    variants: visibility=global
  doxygen:
    version:
    - 1.8.20
  elfutils:
    variants: +bzip2 ~nls +xz
  fftw:
    variants: +openmp
  hdf5:
    variants: +fortran +hl +shared api=v18
    version:
    - 1.12.1
  libfabric:
    variants: fabrics=sockets,tcp,udp,rxm
  libunwind:
    variants: +pic +xz
  mesa:
    variants: ~llvm
  mesa18:
    variants: ~llvm
  mpich:
    variants: ~wrapperrpath
  ncurses:
    variants: +termlib
  openblas:
    variants: threads=openmp
  trilinos:
    variants: +amesos +amesos2 +anasazi +aztec +belos +boost +epetra +epetraext
      +ifpack +ifpack2 +intrepid +intrepid2 +isorropia +kokkos +ml +minitensor +muelu
      +nox +piro +phalanx +rol +rythmos +sacado +stk +shards +shylu +stokhos +stratimikos
      +teko +tempus +tpetra +trilinoscouplings +zoltan +zoltan2 +superlu-dist gotype=long_long
  xz:
    variants: +pic
